version: '3.8'

services:

  app:
    build: gateway
    container_name: fastapi_app
    depends_on:
      - pokemon
      - pokemon_images
      - pokemon_api
#    volumes:
#      - ./config.env:/code/config.env
    ports:
      - "8000:8000"


  pokemon:
    build: pokemon
    container_name: pokemon_container
#    volumes:
#      - ./config.env:/code/config.env
    ports:
      - "8001:8001"

  mysql:
    image: mysql:latest
    container_name: mysql_container
    env_file:
      - ./config.env
    ports:
      - "3306:3306"


  pokemon_images:
    build: pokemon_images
    container_name: images
    depends_on:
      - mongodb
    ports:
      - "8002:8002"
    environment:
      - MONGODB_URL=mongodb://mongodb_container:27017/

  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db


  pokemon_api:
    build: pokemon_api
    container_name: api_service
    ports:
      - "8003:8003"

volumes:
  mongodb_data:
    driver: local
